services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mailwurm\ImgNaviBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources,ContaoManager}'
