services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tonsinn\ImgNaviBundle\:
        resource: '../src/'
        exclude:
            - '../src/ContaoManager/'
            - '../src/DependencyInjection/'
            - '../src/TonsinnImgNaviBundle.php'
